import type { GlobalThemeOverrides } from 'naive-ui'

// Apple iOS/macOS 风格主题
export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#007AFF',
    primaryColorHover: '#0056CC',
    primaryColorPressed: '#0040A0',
    primaryColorSuppl: '#409CFF',
    borderRadius: '12px',
    borderRadiusSmall: '8px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", "Helvetica Neue", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontSize: '15px',
    fontSizeMedium: '15px',
    fontSizeLarge: '16px',
    fontSizeHuge: '18px',
    heightMedium: '38px',
    heightLarge: '44px',
  },
  Button: {
    colorPrimary: '#007AFF',
    colorHoverPrimary: '#0056CC',
    colorPressedPrimary: '#0040A0',
    colorFocusPrimary: '#007AFF',
    borderPrimary: 'none',
    borderHoverPrimary: 'none',
    borderPressedPrimary: 'none',
    borderFocusPrimary: 'none',
    textColorPrimary: '#ffffff',
    textColorHoverPrimary: '#ffffff',
    textColorPressedPrimary: '#ffffff',
    textColorFocusPrimary: '#ffffff',
    borderRadiusMedium: '10px',
    borderRadiusLarge: '12px',
    borderRadiusSmall: '8px',
    fontWeight: '500',
    paddingMedium: '0 20px',
    paddingLarge: '0 24px',
  },
  Card: {
    borderRadius: '16px',
    paddingMedium: '20px',
    borderColor: 'rgba(0, 0, 0, 0.06)',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
  },
  Checkbox: {
    colorChecked: '#007AFF',
    checkMarkColor: '#ffffff',
    borderChecked: '1px solid #007AFF',
    borderFocus: '1px solid #007AFF',
    boxShadowFocus: '0 0 0 2px rgba(0, 122, 255, 0.2)',
    borderRadius: '6px',
  },
  Radio: {
    dotColorActive: '#007AFF',
    buttonColorActive: '#007AFF',
    boxShadowFocus: '0 0 0 2px rgba(0, 122, 255, 0.2)',
  },
  Switch: {
    railColorActive: '#34C759',
    loadingColor: '#34C759',
    buttonBorderRadius: '50%',
    railBorderRadiusMedium: '16px',
  },
  Input: {
    borderHover: '1px solid rgba(0, 122, 255, 0.4)',
    borderFocus: '1px solid #007AFF',
    boxShadowFocus: '0 0 0 3px rgba(0, 122, 255, 0.15)',
    borderRadius: '10px',
    heightMedium: '38px',
    heightLarge: '44px',
    color: '#ffffff',
    colorFocus: '#ffffff',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderHover: '1px solid rgba(0, 122, 255, 0.4)',
        borderFocus: '1px solid #007AFF',
        boxShadowFocus: '0 0 0 3px rgba(0, 122, 255, 0.15)',
        borderRadius: '10px',
        heightMedium: '38px',
      },
    },
  },
  Slider: {
    fillColor: '#007AFF',
    fillColorHover: '#0056CC',
    dotColor: '#ffffff',
    dotColorModal: '#ffffff',
    dotBorderActive: '2px solid #007AFF',
  },
  Progress: {
    fillColor: '#007AFF',
    railColor: 'rgba(0, 122, 255, 0.12)',
  },
  Tag: {
    borderRadius: '8px',
    colorPrimary: 'rgba(0, 122, 255, 0.1)',
    colorBorderedPrimary: 'rgba(0, 122, 255, 0.1)',
    borderPrimary: '1px solid rgba(0, 122, 255, 0.3)',
    textColorPrimary: '#007AFF',
  },
  Badge: {
    colorError: '#FF3B30',
  },
  Tabs: {
    tabTextColorActiveBar: '#007AFF',
    tabTextColorHoverBar: '#0056CC',
    barColor: '#007AFF',
    tabBorderRadius: '8px',
  },
  DataTable: {
    borderRadius: '12px',
    thColor: 'rgba(0, 0, 0, 0.02)',
    thTextColor: '#86868b',
    thFontWeight: '600',
    tdColor: '#ffffff',
    tdColorHover: 'rgba(0, 122, 255, 0.04)',
    borderColor: 'rgba(0, 0, 0, 0.06)',
    thPaddingMedium: '14px 16px',
    tdPaddingMedium: '14px 16px',
  },
  Modal: {
    borderRadius: '16px',
    boxShadow: '0 24px 48px rgba(0, 0, 0, 0.12), 0 12px 24px rgba(0, 0, 0, 0.08)',
  },
  Dialog: {
    borderRadius: '16px',
  },
  Menu: {
    borderRadius: '10px',
    itemColorActive: 'rgba(0, 122, 255, 0.1)',
    itemColorActiveHover: 'rgba(0, 122, 255, 0.15)',
    itemTextColorActive: '#007AFF',
    itemTextColorActiveHover: '#007AFF',
    itemIconColorActive: '#007AFF',
    itemIconColorActiveHover: '#007AFF',
    itemColorHover: 'rgba(0, 0, 0, 0.04)',
  },
  Notification: {
    borderRadius: '14px',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12)',
  },
  Message: {
    borderRadius: '12px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.1)',
  },
  Popconfirm: {
    borderRadius: '12px',
  },
  Breadcrumb: {
    fontSize: '14px',
    fontWeightActive: '600',
  },
  Form: {
    labelFontWeight: '500',
  },
  Statistic: {
    labelFontWeight: '500',
  },
}
